# 02_profile_dove.R -----------------------------------------------------------
#
# Profile the schema of a Dove snapshot and write a committed schema note.
#
# WHY THIS IS ITS OWN STEP
#   Dove's field list is not guaranteed stable ("the number and order of the
#   fields may change from time to time"). Writing frame-building code against
#   a remembered schema is how you get silent wrong answers. This step reads
#   what is actually there, writes it down, and commits it. The note in
#   provenance/ then becomes the thing that changes visibly in a diff when Dove
#   changes under you.
#
# Output: provenance/dove_schema_<snapshot_id>.md  (small, committed, no data)

source(here::here("scripts", "00_setup.R"))

# ---- locate the snapshot ----------------------------------------------------

snap <- latest_snapshot_dir("dove")
if (is.na(snap)) stop("No Dove snapshot found. Run scripts/01_fetch_dove.R first.", call. = FALSE)

snapshot_id <- paste0("dove_", fs::path_file(snap))
message("Profiling snapshot: ", snapshot_id)

# Verify the bytes are the ones we recorded. Cheap, and it catches a
# half-finished download or an edited-in-place "fix".
log_rows <- read_fetch_log() |> dplyr::filter(.data$snapshot_id == !!snapshot_id)
purrr::pwalk(
  log_rows |> dplyr::select(file, sha256),
  \(file, sha256) verify_sha256(fs::path(snap, file), sha256)
)
message("Checksums verified against provenance/fetch_log.csv.")

# ---- read as character ------------------------------------------------------
# Everything as character on purpose: we are profiling what is in the file, not
# what readr guesses it means. Type decisions belong in 03, made deliberately.

files <- fs::dir_ls(snap, glob = "*.csv")
tabs  <- purrr::map(files, \(f) readr::read_csv(f, col_types = readr::cols(.default = "c")))
names(tabs) <- fs::path_ext_remove(fs::path_file(files))

# ---- profile ----------------------------------------------------------------

profile_column <- function(x, name) {
  non_na <- x[!is.na(x) & x != ""]
  tibble::tibble(
    column     = name,
    n_missing  = sum(is.na(x) | x == ""),
    pct_missing = round(100 * (sum(is.na(x) | x == "") / length(x)), 1),
    n_distinct = dplyr::n_distinct(non_na),
    min_chars  = if (length(non_na)) min(nchar(non_na)) else NA_integer_,
    max_chars  = if (length(non_na)) max(nchar(non_na)) else NA_integer_,
    examples   = paste(utils::head(unique(non_na), 3), collapse = " | ")
  )
}

profile_table <- function(tab) {
  tab |>
    purrr::imap(profile_column) |>
    purrr::list_rbind()
}

profiles <- purrr::map(tabs, profile_table)

# ---- low-cardinality columns get a frequency table --------------------------
# These are the ones that turn out to be flags and classifications — the fields
# that decide frame inclusion. Worth seeing in full.

freq_tables <- purrr::imap(tabs, function(tab, tname) {
  low_card <- profiles[[tname]] |>
    dplyr::filter(.data$n_distinct > 0, .data$n_distinct <= 25) |>
    dplyr::pull(.data$column)

  purrr::map(rlang::set_names(low_card), function(cn) {
    tab |>
      dplyr::count(value = .data[[cn]], sort = TRUE, name = "n") |>
      utils::head(25)
  })
})

# ---- write the note ---------------------------------------------------------

out <- here::here("provenance", paste0("dove_schema_", snapshot_id, ".md"))
con <- file(out, open = "w")
on.exit(close(con))

wl <- function(...) writeLines(paste0(...), con)

wl("# Dove schema note — ", snapshot_id)
wl("")
wl("Generated by `scripts/02_profile_dove.R` on ",
   format(Sys.time(), tz = "UTC", "%Y-%m-%d %H:%M:%S"), " UTC.")
wl("")
wl("Source data: Dove's Guide for Church Bell Ringers (https://dove.cccbr.org.uk),")
wl("CC BY-SA 4.0. This note contains schema metadata and value frequencies only.")
wl("")

for (tname in names(tabs)) {
  wl("## ", tname, ".csv")
  wl("")
  wl("Rows: ", format(nrow(tabs[[tname]]), big.mark = ","),
     "  |  Columns: ", ncol(tabs[[tname]]))
  wl("")
  wl(paste(knitr::kable(profiles[[tname]], format = "pipe"), collapse = "\n"))
  wl("")

  ft <- freq_tables[[tname]]
  if (length(ft)) {
    wl("### Low-cardinality columns (<= 25 distinct)")
    wl("")
    for (cn in names(ft)) {
      wl("**", cn, "**")
      wl("")
      wl(paste(knitr::kable(ft[[cn]], format = "pipe"), collapse = "\n"))
      wl("")
    }
  }
}

message("Schema note written to:\n  ", out)
message("\nCommit it. It is the record of what Dove looked like when the frame was built.")

# -----------------------------------------------------------------------------
# WHAT TO LOOK FOR when you read the note — these decide the frame:
#
#   * The stable tower identifier. Its name, its format, whether it is unique.
#     Everything downstream keys on it and the questionnaire must capture it.
#   * Bell count, and whether rings of 1 and 2 appear.
#   * Any "unringable" / "out of order" / status flag, and its value set.
#   * The affiliation field: one column or several, delimiter, code vocabulary.
#     This is the join to the CCCBR society membership table.
#   * Country / region columns, for the geographic scope decision.
#   * Place vs "place with common name" variants — which one a ringer recognises.
# -----------------------------------------------------------------------------
